### ISSUE TITLE
Removing old logs and keeping new Logs

### ISSUE THREAD

**Issue by lchsam** [samdenty99/console-feed#5]
Hi,
I am trying to implement a logging component that incrementally deletes old logs when there are too many logs.
I noticed that console-feed does not rerender properly when I delete and add new logs.

Have a look at this example: https://codesandbox.io/s/x9wpm9w1vz
Try pressing the new log button.

Thanks!

**Comment by arthurdenner** [comment]
The cause of this problem is that we are using the `index` as the `key` [here](https://github.com/samdenty99/console-feed/blob/master/src/Component/index.tsx#L32).

I thought about using `${log.method}-${i}` as the `key`, this may be enough to solve the problem.

@samdenty99, what do you think? I have a PR ready to submit if you agree with this solution.
